CREATE DATABASE dbcontroleprojeto
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'Portuguese_Brazil.1252'
       LC_CTYPE = 'Portuguese_Brazil.1252'
       CONNECTION LIMIT = -1;

CREATE TABLE projeto (
   ID INTEGER CONSTRAINT PROJETO_ID_PK PRIMARY KEY NOT NULL,
   NOME TEXT NOT NULL,
   DESCRICAO TEXT,
   SITUACAO CHAR(255),
   ORCAMENTO NUMERIC(10,2)	
);

CREATE TABLE estado (
   ID INTEGER CONSTRAINT ESTADO_ID_PK PRIMARY KEY NOT NULL,
   NOME VARCHAR(100) NOT NULL
);

--select column_name, data_type, character_maximum_length
--from INFORMATION_SCHEMA.COLUMNS where table_name = 'estado';
--SELECT * FROM ESTADO;

CREATE TABLE cidade (
   ID INTEGER CONSTRAINT CIDADE_ID_PK PRIMARY KEY NOT NULL,
   NOME VARCHAR(100),
   ESTADO_ID INTEGER,
    CONSTRAINT CIDADE_ESTADO_FKEY FOREIGN KEY (ESTADO_ID)
      REFERENCES ESTADO (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

select column_name, data_type, character_maximum_length
from INFORMATION_SCHEMA.COLUMNS where table_name = 'cidade';

CREATE TABLE departamento (
   ID INTEGER CONSTRAINT DEPARTAMENTO_ID_PK PRIMARY KEY NOT NULL,
   NOME TEXT NOT NULL,
   DESCRICAO TEXT,
   ORCAMENTO NUMERIC(10,2),
   RAMAL INTEGER
);

CREATE TABLE colaborador (
   ID INTEGER CONSTRAINT COLABORADOR_ID_PK PRIMARY KEY NOT NULL,
   NOME TEXT,
   SEXO CHAR(1),
   DATA_NASCIMENTO DATE,
   REMUNERACAO NUMERIC(6,2),
   EMAIL VARCHAR(100),
   DEPARTAMENTO_ID INTEGER,
   CONSTRAINT COLABORADOR_DEPARTAMENTO_FKEY FOREIGN KEY (DEPARTAMENTO_ID)
      REFERENCES DEPARTAMENTO (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE alocacao (
   ID INTEGER CONSTRAINT ALOCACAO_ID_PK PRIMARY KEY NOT NULL,
   CARGA_HORARIA NUMERIC(3,2),
   SITUACAO INTEGER,
   COLABORADOR_ID INTEGER,
   PROJETO_ID INTEGER,
   CONSTRAINT ALOCACAO_COLABORADOR_FKEY FOREIGN KEY (COLABORADOR_ID)
      REFERENCES COLABORADOR (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
   CONSTRAINT ALOCACAO_PROJETO_FKEY FOREIGN KEY (PROJETO_ID)
      REFERENCES PROJETO (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);